XrmToolBox/MainForm.cs

I've created three asynchronous tasks:
* Showing splash screen;
* Loading available plugins;
* Checking new version;
They are starting working simultaneously on program load. When they are all done, main window show up.

Splash screen optimizations

---

README.md

Just simple change to make README.md look more pretty.

Adding new line to README.md to make gitter bage look nicely

---

index.html

The counter was actually just myltiplying download count of latest release with the number of releases...

Fixed All Downloads counter

---

Connection Projects/McTools.Xrm.Connection.WinForms/ConnectionForm.cs

Correcting HTTPS port number. Fixes #31

---

Plugins/MsCrmTools.AssemblyRecoveryTool/MainControl.Designer.cs
Plugins/MsCrmTools.AssemblyRecoveryTool/MainControl.cs

Minor bugfixes for Assembly Recovery Tool

---

XrmToolBox/MainForm.Designer.cs
XrmToolBox/MainForm.cs
XrmToolBox/MainForm.resx
XrmToolBox/UserControls/PluginModel.Designer.cs
XrmToolBox/UserControls/SmallPluginModel.Designer.cs

Possible Fix for Issue #64 
Modified the Auto scale property of the MainForm, the PluginModel and the SmallPluginModel to set it to scale on DPI instead of Font.
Changed the code on MainForm DisplayOnePlugin() to increase the Top value by the size of the plugin control and 4 pixels spacer.

Fix scaling issue on Plugin List Issue

---

Connection Projects/McTools.Xrm.Connection.Console/McTools.Xrm.Connection.Console.csproj
Connection Projects/McTools.Xrm.Connection.TestWinForm/McTools.Xrm.Connection.TestWinForm.csproj
Connection Projects/McTools.Xrm.Connection.WinForms/McTools.Xrm.Connection.WinForms.csproj
Connection Projects/McTools.Xrm.Connection.WinForms/app.config
Connection Projects/McTools.Xrm.Connection/McTools.Xrm.Connection.csproj
Connection Projects/McTools.Xrm.Connection/app.config

Cleaning up connection projects (references to binary files was found in project files)

Removing references to unused files

---

Connection Projects/McTools.Xrm.Connection.Console/McTools.Xrm.Connection.Console.csproj
Connection Projects/McTools.Xrm.Connection.TestWinForm/McTools.Xrm.Connection.TestWinForm.csproj
Connection Projects/McTools.Xrm.Connection.WinForms/McTools.Xrm.Connection.WinForms.csproj
Connection Projects/McTools.Xrm.Connection.WinForms/app.config
Connection Projects/McTools.Xrm.Connection/McTools.Xrm.Connection.csproj
Connection Projects/McTools.Xrm.Connection/app.config
Plugins/MsCrmTools.MetadataBrowser/Forms/ColumnSelector.Designer.cs
Plugins/MsCrmTools.MetadataBrowser/MainControl.Designer.cs
Plugins/MsCrmTools.MetadataBrowser/MainControl.cs
Plugins/MsCrmTools.MetadataBrowser/UserControls/EntityPropertiesControl.Designer.cs

Entities are loaded automatically on plugin start, grid lines added to the list view controls.

Small usability improvements

---

XrmToolBox/MainForm.Designer.cs
XrmToolBox/MainForm.cs

* Disabling search box if Home screen is invisible (and enabling it when it become visible again);
* Focus on plugins filter box on Ctrl+F;

Small usability improvements for plugin search

---

XrmToolBox/MainForm.cs

The reasons:
* Noticeable speed drop;
* Control re-drawing issues;

Reverting anti-flickering

---

XrmToolBox/Forms/NewVersionForm.cs

Added support for custom download url in the NewVersionForm.

VersionChecker support for custom download url

---

XrmToolBox/MainForm.cs
XrmToolBox/MessageBusEventArgs.cs

Improvements using real life examples from @rappen and according to his comments.

Message bus improvements

---

XrmToolBox/UserControls/LargePluginModel.Designer.cs
XrmToolBox/UserControls/SmallPluginModel.Designer.cs

Once you noticed that images are not square, you cannot work any further. So I fixed it.

Making plugin images be square

---

XrmToolBox/PluginManager.cs

Right now it would be possible to check wherever plugin was loaded by calling static method:
```
if (PluginManager.IsLoaded("Plugin Title"))
{
...
}
```

Adding static method to check was plugin loaded or not

---

Plugins/MsCrmTools.UserRolesManager/AppCode/RoleManager.cs

As I said in the bug #130, this is the fix. And also it is my first pull request! hurey

Fixing #130 - Assign roles, different business units

---

XrmToolBox/AppCode/LogUsage.cs

Should be Allow XrmToolBox to Collect Anonymous usage Statistics

Fixed English

---

XrmToolBox/MainForm.resx

Error message points to correct resolution of issue.

Correcting error message. Closes #160

---

XrmToolBox/MainForm.Designer.cs
XrmToolBox/MainForm.cs

Search will try to autocomplete name of the plugin.
Pressing `Enter` will start selected plugin.

Start plugin from search box

---

Plugins/Javista.XrmToolBox.ImportNN/MainControl.Designer.cs
Plugins/Javista.XrmToolBox.ImportNN/MainControl.cs

Service instance was always null during import and import operations.

Fixing unassigned service usage #198

---

Plugins/MsCrmTools.FormRelated/FormLibrariesManager/Forms/FormEventsDialog.Designer.cs
Plugins/MsCrmTools.FormRelated/FormLibrariesManager/Forms/FormEventsDialog.cs
Plugins/MsCrmTools.FormRelated/FormLibrariesManager/Forms/FormEventsDialog.resx
Plugins/MsCrmTools.FormRelated/MsCrmTools.FormRelated.csproj

Added Default Values for Handlers

Fixed Build Error where Resource files wasn't included.  Just Removed it

---

Plugins/MsCrmTools.MetadataDocumentGenerator/Generation/ExcelDocument.cs

fixed nullReference exception when user wants to generate metadata for foreign language and his translations are incompleted (missing translations)

Update ExcelDocument.cs 

---

XrmToolBox/MainForm.cs

Simple trick to improve UI experience: sometimes depending on PC configuration it's possible to see flickering during resize of plugin list (best place to see this effect so far)

Adding optimized doube buffering to prevent flickering

---

Plugins/MsCrmTools.SecurityRelated/UserRolesManager/AppCode/RoleManager.cs

Allow to update role in organization with table role bigger than 5000 records

Update User Role Manager to correct issue #376

---

XrmToolBox/Forms/PluginsChecker.cs

The nuget package with the plugin should contain a dependency specification for ``XrmToolBox`` and the highest available XrmToolBox version for which the plugin is compiled.
Example:
```
<package >
<metadata>
<id>Cinteros.Xrm.FetchXMLBuilder</id>
... a bunch of other properties ...
<tags>XrmToolBox Plugins FetchXML Builder</tags>
<dependencies>
<dependency id="XrmToolBox" version="1.2016.3.30" />
</dependencies>
</metadata>
<files>
... some files ...
</files>
</package>
```

#327 Check version dependency for plugins to verify compatibility

---

XrmToolBox/Forms/PluginsChecker.Designer.cs
XrmToolBox/Forms/PluginsChecker.cs
XrmToolBox/Forms/PluginsChecker.resx

And some refactoring.
Still a bit shaky determination of current plugin version... see ``TODO:`` in code.

Fixed NuGet deploy of all file types for plugins

---

Plugins/MsCrmTools.WebResourcesManager/AppCode/Options.cs
Plugins/MsCrmTools.WebResourcesManager/AppCode/TreeViewHelper.cs
Plugins/MsCrmTools.WebResourcesManager/AppCode/WebResource.cs
Plugins/MsCrmTools.WebResourcesManager/Forms/OptionsDialog.Designer.cs
Plugins/MsCrmTools.WebResourcesManager/Forms/OptionsDialog.cs
Plugins/MsCrmTools.WebResourcesManager/UserControls/WebresourceTreeView.cs
Plugins/MsCrmTools.WebResourcesManager/WebResourcesManager.cs

Added Ability to Check in .Map files and TypeScriptFiles.  
This allows for debugging TS in Chrome (and potentially other browsers).
Cleaned up duplicate Loading of Files from disk.
Added setting for Turning Feature on

Added Ability to Check in .Map files and TypeScriptFiles.  

---

Plugins/MsCrmTools.SampleTool/SampleTool.Designer.cs
Plugins/MsCrmTools.SampleTool/SampleTool.cs

When I first tried SampleCode , I thought I had a bug - infinite loop. I had to read the code to understand what was really expected.
I think it should be useful to choose to make multiple calls or not.  An option has been added on the form.
This plugin is very helpful, may be other options could be added.

multiple calls option added

---

XrmToolBox.Extensibility/PluginCloseInfo.cs
XrmToolBox.Extensibility/PluginControlBase.cs
XrmToolBox/Forms/OptionsDialog.Designer.cs
XrmToolBox/Forms/OptionsDialog.cs
XrmToolBox/MainForm.cs
XrmToolBox/Options.cs

Added new option checkbox and code to respect that option when closing plugins.

Fixing #466 Option to close plugins without prompt

---

XrmToolBox.Extensibility/Interfaces/IXrmToolBoxPlugin.cs
XrmToolBox.Extensibility/PluginBase.cs
XrmToolBox/MainForm.PluginsManagement.cs

More robust handling of plugins models was introduced to avoid situations like #557 in the future.

Fix for #557

---

XrmToolBox/Forms/OptionsDialog.Designer.cs
XrmToolBox/Forms/OptionsDialog.cs
XrmToolBox/MainForm.cs
XrmToolBox/Options.cs

1. Add new setting in Misc tab to enable session restore (tool and connection)
2. Persist Tool and Connection name to XrmToolBox xml setting before close
3. Use the setting file to automatically connect and focus the right tool upon re-open (#575)
2. Fix NullReferenceException in GetVisibleScrollbars (#536)

Session restore (last connection & tool)

---

.gitignore

Ignore everything within folder .vs folder

Ignore everything within folder

---

XrmToolBox.PluginsStore/DTO/XtbPlugin.cs
XrmToolBox.PluginsStore/StoreFromPortal.cs

When the host is not found or any exception in the process of getting plugins from the store will stop the app, so catching the exception and suppressing it.

Fixed #828

---

XrmToolBox.PluginsStore/StoreFromPortal.cs

now checks for null before parsing

fix issue parsing connection control version

---

XrmToolBox.PluginsStore/StoreFromPortal.cs

need to ensure Version can parse the string

additional check for version string

---

XrmToolBox.Extensibility/SettingsManager.cs

Added a try catch to show the path of the file that is failing to deserialize.  This is helpful for users to understand what file they may need to look at.
Moved logic that is duplicated to methods that are reused between the save and the load.

Added Serialization Error File Path

---

Plugins/MsCrmTools.SampleTool/SampleTool.cs
XrmToolBox.Extensibility/Interfaces/IPluginComposedMetadata.cs
XrmToolBox.Extensibility/Manifest/Manifest.cs
XrmToolBox.Extensibility/Manifest/ManifestLoader.cs
XrmToolBox.Extensibility/Manifest/PluginMetadata.cs
XrmToolBox.Extensibility/UserControls/LargePluginModel.cs
XrmToolBox.Extensibility/UserControls/SmallPluginModel.cs
XrmToolBox.Extensibility/XrmToolBox.Extensibility.csproj
XrmToolBox.PluginsStore/StoreFormFromPortal.cs
XrmToolBox.PluginsStore/StoreFromPortal.cs
XrmToolBox/Forms/DonationIntroForm.cs
XrmToolBox/Forms/HiddenPluginsDialog.cs
XrmToolBox/New/NewForm.cs
XrmToolBox/New/PluginsForm.cs
XrmToolBox/PluginManagerExtended.cs
XrmToolBox/XrmToolBox.csproj

Added: plugin cache to speed up startup time.
Improved: store update check speed on startup.

Speed up tool startup performance.

---

XrmToolBox/XrmToolBox.csproj
XrmToolBox/packages.config

Fixed: DockPanelSuite new version is incompatible with some existing plugins.

Fixed: backward compatibility of some packages.

---

Plugins/MsCrmTools.SampleTool/SampleTool.Designer.cs
Plugins/MsCrmTools.SampleTool/SampleTool.cs
Plugins/MsCrmTools.SampleTool/SampleTool.resx
XrmToolBox.Extensibility/Forms/ErrorDetail.cs
XrmToolBox.Extensibility/Forms/ErrorDetail.designer.cs
XrmToolBox.Extensibility/Forms/ErrorDetail.resx
XrmToolBox.Extensibility/PluginControlBase.cs
XrmToolBox.Extensibility/XrmToolBox.Extensibility.csproj

Error Detail for "everything"... it should handle any kind of `Exception` or any descendants class.
Code:
```
/// <summary>
/// Generic Error Details show a dialog
/// </summary>
/// <param name="exception">Exception or any descendants class</param>
/// <param name="heading">Title of the problem the tool want to show. Null = 'Error Detail'</param>
/// <param name="extrainfo">If the tool may have more information, this will be used to a new issue.</param>
/// <param name="allownewissue">If tool is `IGitHubPlugin` and send this as True new issues can be added by the user.</param>
public void ShowErrorDialog(Exception exception, string heading = null, string extrainfo = null, bool allownewissue = true)
```

Error Detail added as generic error message

---

XrmToolBox.Extensibility/Forms/ErrorDetail.designer.cs

Some small more...
* Aligning properly left/right, both text and buttoms
* Removed padding test
* Change "Bring to Front" to show Close button etc.
I think that's it 🙂

Minow layout for ErrorDetail

---

XrmToolBox.Extensibility/Forms/ErrorDetail.cs
XrmToolBox.Extensibility/Forms/ErrorDetail.designer.cs

Error aligned and #1123

---

XrmToolBox/PluginManagerExtended.cs

Fixed I and ı (Turkish equivalent of lower I) problem during loading plugins.

Fixed ToLower() Problem For Turkish Locale #1194

---

XrmToolBox/Program.cs

Symptom: Xrm Toolbox won't open. Visible in task manager.
Cause: `%APPDATA%\XrmToolBox\Update.xml` has a `<PreviousProcessId>` that contains the PID of an unrelated process.
Fix: verify process name before waiting
Possible future follow up would be to switch to a named mutex or similar based on the plugin directory name, to support multiple instances.

fix issue where the PID of previous process is reused during plugin update

---

XrmToolBox/PluginManagerExtended.cs

Basic logic is to add a handler for the AssemblyResolve event, and whenever the assembly isn't found, it searches all the child directories of the plugin folder, and reads the assembly type names.  Then when an assembly is being requested and not found, it loads it from the already discovered assemblies, returning null if there wasn't any item found.

Fix for [BUG] Unable to Specify Assembly Resolve Handler #1280

---

XrmToolBox.Extensibility/Manifest/ManifestLoader.cs
XrmToolBox/PluginManagerExtended.cs

Assemblies aren't getting loaded correctly if the manifest.json already exists.  Also moved away from referencing the Plugin attribute (maybe this shouldn't have been done, or maybe it should be deleted rather that obsoleted?)

Fix for null error on Assembly load

---

XrmToolBox.ToolLibrary/Forms/ToolLibraryForm.cs
XrmToolBox/Options.cs

Remove Use Legacy Tool Library 
Display error message to user when Tool Library failed to load

Tool library changes
