- XrmToolBox/MainForm.Designer.cs
- XrmToolBox/MainForm.cs
The splash-screen code was reorganized to avoid usage of `BackgroundWorker`. `async` and `await` approach was used instead.
The code waits whatever will be finished first: plugins loading or 3 seconds splash-screen display delay and continues form loading.
> Correcting splash-screen behavior

- Plugins/MsCrmTools.MetadataDocumentGenerator/MsCrmTools.MetadataDocumentGenerator.csproj
- Plugins/MsCrmTools.Translator/MsCrmTools.Translator.csproj
- Plugins/MsCrmTools.WebResourcesManager/MsCrmTools.WebResourcesManager.csproj
Some plugins does not compile, since their dependencies are not installed to `Program Files`, but most of the needed assemblies are already present as `NuGet` packages within repository. Correcting links to make use `NuGet` files instead of `Program Files` ones.
> Correcting references to plugin dependencies

- XrmToolBox/MainForm.cs
I have found several places, where cross-thread error might pop-up.
* In case if was no plugins were found in `XrmToolBox` folder;
* In case list of controls on main panel is not empty at the moment of application start (I don't know how this might happen?, but still)
> In case if no plugins cross-thread error will pop-up.

- XrmToolBox/PluginManager.cs
Simple optimization to speed-up XrmToolBox loading.
I've made simple test on efficiency. I've run 10 times each approach on 24 plugins. Here is results:
Case no. | Serial execution (milliseconds)| Parallel execution (milliseconds)
--- | ---------------- | ------------------
1 | 398 | 321
2 | 384 | 313
3 | 426 | 281
4 | 367 | 281
5 | 390 | 319
6 | 429 | 301
7 | 397 | 316
8 | 397 | 305
9 | 344 | 284
10 | 329 | 326
**Average** | 386.1 | 304.7
**Percentage** | 100% | 78.92 %
21.08% performance gain on 4 logical cores CPU.
> Loading plugins in parallel at application start up

- Plugins/MsCrmTools.AssemblyRecoveryTool/MainControl.cs
If `Load assemblies` button is pressed more than once in `AssemblyRecoveryTool`, list of assemblies is not cleared. Duplicate entries added instead.
> Clearing list of already loaded assemblies

- Connection Projects/McTools.Xrm.Connection.WinForms/ConnectionForm.cs
- Connection Projects/McTools.Xrm.Connection.WinForms/ConnectionForm.designer.cs
- Connection Projects/McTools.Xrm.Connection.WinForms/ConnectionSelector.designer.cs
Closing dialogs with `ESC` — way quicker!
> Small usability improvements

- Plugins/MsCrmTools.AssemblyRecoveryTool/MainControl.cs
Wiring up the `ConnectionUpdated` event of the Assemblies Recovery Tool to be able update list of current organization assemblies, if user chooses to update selected tabs.
> Initiate update of the available assemblies

- XrmToolBox/MainForm.cs
Reverting asynchronous plugin loading, since there are some cases, when plugin can fail to load (depends on set of the UI properties modified during plugin initialization)
> Loading plugins synchronously. Fixes #56

- XrmToolBox/MainForm.cs
- XrmToolBox/PluginCloseInfo.cs
This PR does not close #44, but introduces additional way to close plugin in addition to mouse middle click on plugin's header.
> Close current plugin using Ctrl+F4 hotkey 

- XrmToolBox/MainForm.cs
- XrmToolBox/Program.cs
I left this feature undocumented for end users, but most probably it is interesting for developers. When developing plugin you cannot start it directly, since it's a class library. 
As a way out you're changing `Start action` of the project to the option `Start external program` and pointing to the `XTB` executable in the `Debug` folder.
This works fine, but you still need to perform following actions: 
* choose connection;
* open needed plugin;
To solve this case new command line parameters was added. It is possible to start `XTB` by following statement:
```
XrmToolBox.exe /connection:"Connection Name" /plugin:"Plugin Name"
```
* `Connection Name` is the same as written in ConnectionManager, for example "CRM DEV";
* `Plugin Name` is the same as official plugin's name, for example "A …
> Introducing command line parameters

- Plugins/MsCrmTools.ScriptsFinder/ScriptsFinder.cs
The formatstring only had placeholders for 10 arguments when (including the newline) there are 11 arguments being passed in.
> Updated the string.format formatstring

- Plugins/MsCrmTools.SiteMapEditor/SiteMapEditor.cs
Check prevents `XTB` from crash when SiteMap is not yet loaded into plugin.
> Adding check on `null`

- XrmToolBox.Extensibility/UserControls/LargePluginModel.Designer.cs
Now plugin models in a bit more `loose` design, so no overlapping of letters will occur.
> Creating a bit more `loose` design of the large plugin model lables

- XrmToolBox/MainForm.PluginsManagement.cs
- XrmToolBox/MainForm.cs
- XrmToolBox/PluginManagerExtended.cs
- XrmToolBox/PluginUseCount.cs
There is a problem with Message Bus.
When migration to `MEF` occurred, a lot of confusion was introduced to code. Before that it was only two possible types of input arguments to plugin manipulation functions: 
* the actual plugin control
* the plugin model (plugin representation in plugins list)
Currently third type was added: `Lazy<IXrmToolBoxPlugin, IPluginMetadata>`. And calls to previous objects was not eliminated, but these objects itself has become obsolete. 
The worst part of it that variable `PluginManagerExtended.PluginsControls` become obsolete. It always empty. And since `Message Bus` relays on this object it stopped working.
I developed the fix and tried to unify approaches. To use `Lazy<IXrmToolBoxPlugin, IPluginMetadata>` everywhere. But this lead to one unpleasant effect. …
> Unifying plugin handling after MEF migration fixes Message Bus

- XrmToolBox.Extensibility/Interfaces/IWorkerHost.cs
- XrmToolBox.Extensibility/PluginControlBase.cs
I've created shortcut for calling asynchronous operations that do not require callback function to be executed.
So if previously you would wrote code like this:
```
this.WorkAsync("Saving changes",
a =>
{
this.Service.Update(entity);
},
a =>
{
});
```
Currently it would be just enough to wrote a bit smaller piece of code:
```
this.WorkAsync("Saving changes",
a =>
{
this.Service.Update(entity);
});
```
Not a huge difference, but makes code cleaner.
> WorkAsyc shortcut for operations that don't require callback

- Connection Projects/McTools.Xrm.Connection/ConnectionManager.cs
- Connection Projects/McTools.Xrm.Connection/Properties/AssemblyInfo.cs
This change introduces the possibility to specify static property ConfigurationFile on the ConnectionManager class.
Sample code to place file ``Connections.config`` in current user's AppData folder for ``Sample App``:
```
ConnectionManager.ConfigurationFile = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "Sample App", "Connections.config");
```
> Specify ConfigurationFile on ConnectionManager

- XrmToolBox/AppCode/GithubVersionChecker.cs
- XrmToolBox/AppCode/Markdown.cs
More forgiving treatment of release notes, as the Markdown transformer unexpectedly fails sometimes.
> Handle release note parsing errors in GithubVersionChecker

- XrmToolBox/AppCode/WebProxyHelper.cs
> Use default credentials when getting settings from IE

- XrmToolBox/Forms/WelcomeDialog.cs
`ManageLicense()` method in `WelcomeDialog.cs` is not optimal. It designed in the way to fire an exception if `McTools.StopAdvertisement.dll` was not found, and after hide this exception as not important.
Not a big deal actually, and does not affect users either, through still annoying during `XrmToolBox` development / debugging, since it fires all the time.
This is small fix checks presence of file on disk in advance, before trying to access it, thus avoiding unnecessary exception.
> Avoiding firing and hiding exception during startup advertisement check

- XrmToolBox.Extensibility/Worker.cs
Following code will be executed, but informational panel won't be closed:
```
var instruction = new WorkAsyncInfo()
{
Message = "Refreshing assemblies information...",
Work = (worker, argument) =>
{
try
{
OrganizationHelper.RefreshConnection(this.m_org, OrganizationHelper.LoadMessages(this.m_org));
Invoke(new Action(() =>
{
propGridEntity.SelectedObject = null;
LoadNodes();
}));
}
catch (Exception ex)
{
Invoke(new Action(() =>
{
ErrorMessageForm.ShowErrorMessageBox(this, "Unable to the refresh the organization. Connection must close.", "Connection Error", ex);
}));
}
}
};
WorkAsync(instruction);
```
To make it work  again empty `PostWorkCallBack` should be defined:
```
var instruction = new WorkAsyncInfo()
{
Message = "Refreshing assemblies information...",
Work = (worker, argument) =>
{ …
```
> Information panel not closed if PostWorkCallBack is not defined

- Plugins/MsCrmTools.MetadataDocumentGenerator/Generation/ExcelDocument.cs
The SDK reports -1 as default value when there's no default value assigned. When extracting a picklist attribute the -1 gets in the excel file. 
Updated document generation to print "N/A" as default when SDK reports -1.
> Metadoc generator: Default picklist value "N/A" instead of "-1" when not set.

- XrmToolBox/Forms/PluginsChecker.cs
- XrmToolBox/Program.cs
Ref #327.
Plugins may now contain a folder structure below the ``Plugins`` folder.
NOTE: Only "assemblies" will be copied, that is dll's and exe's.
> NuGet Plugin Updater supporting assembly files in subfolder of Plugins folder

- Plugins/MsCrmTools.AssemblyRecoveryTool/AppCode/AssemblyManager.cs
- Plugins/MsCrmTools.AssemblyRecoveryTool/MainControl.cs
`ART` now is not asking for binary contents of all assemblies, but only for these that user have chosen.
This actually significantly improves performance on systems with large number of assemblies.
> Correcting behavior of Assembly Recovery Tool

- XrmToolBox/Forms/PluginsChecker.Designer.cs
- XrmToolBox/Forms/PluginsChecker.cs
- XrmToolBox/Forms/PluginsChecker.resx
- XrmToolBox/ProxySettingsHelper.cs
- XrmToolBox/XrmToolBox.csproj
This version is "experimental" and will be enhances with user feedbacks. I have only tested it with my corporate proxy.
An option "Proxy settings" has been added to the Plugins Store f
orm.
The proxy settings Form existing in MscrmTools.Xrm.Connection has been used:
XrmToolbox has to be restarted in order for changes to take effect.
ProxySettingsHelper has been added for this feature.
> proxy settings added for plugins store

- XrmToolBox/MainForm.cs
Save scrollbar position for HomePageTab before RequestCloseTab, and set it again after tool has closed.
> Issue# 443: Fix to retain scrollbar position after tool close

- XrmToolBox.Extensibility/PluginControlBase.cs
- XrmToolBox/AppDomainProxyTypeHack.cs
- XrmToolBox/MainForm.PluginsManagement.cs
- XrmToolBox/Program.cs
- XrmToolBox/XrmToolBox.csproj
This change will allow the CRM ToolBox To Connect, even if multiple plugins are currently loaded with ProxyTypes Enabled.
It will allow for CrmContext interactions, but only if the plugin implements IEarlyBoundProxy, and only for one plugin assembly type per instance of XrmToolBox
Known Breaking Changes introduced:
If a plugin is using an OrganizationServiceContext without implementing IEarlyBoundProxy, it will fail upon attempts to interact to CRM via the OrganizationServiceContext.
Known Bugs introduced
If two plugins implement IEarlyBoundProxy, and define two different assemblies with at least one type of the same logical name, when the second plugin loads, and exception will be thrown.
For some reason the SetEarlyBoundAssembly method doesn't appear to be working with this change. It …
> Hack for Early Bound Assemblies

- XrmToolBox/Forms/TabConnectionUpdater.Designer.cs
- XrmToolBox/Forms/TabConnectionUpdater.cs
Added button "All tabs" to update connection for all tabs with one click.
Changed name of existing buttons to "No tabs" and "Checked tabs" for clarity and consistence.
> Improved buttons in TabConnectionUpdater dialog

- .gitignore
- XrmToolBox/MainForm.cs
Consider that you open two tabs with plugins, (can be the same plugin).
Then you close the first tab and then try to close the second.
Now that is fixed so the correct tab always is closed.
> Small fix to close the correct tab

- XrmToolBox.PluginsStore/ListViewItemComparer.cs
Fix for #740 
decimal.TryParse can convert string with group separators and decimal periods correctly.
> Comparer for plugin store is comparing number incorrectly #740

- XrmToolBox/New/NewVersionForm.cs
The modified code will prevent an IOException when copying the updater if the source path is the same as the destination path.
> Prevent exception on update

- XrmToolBox.AutoUpdater/AutoUpdater.cs
When the path of XrmToolBox contains at leat one space, this path is splitted in many args. The path must be rebuilt before adding quote.
If not, an exception of type "not found "  will be thrown because the path is not complete.
> Exception on update: handle case when path of xrmtoolbox.exe contains at leat one space

- XrmToolBox/Program.cs
- XrmToolBox/XrmToolBox.csproj
Trying to debug my plugin using `/overridepath:.` command line switch. `XTB` was giving me an error "File is used by another application" mentioning my plugin. That was very strange and I downloaded the source.
It turned out that `Path.GetFullPath` method resolved path differently depending upon was it initially given as relative or not. It was very small difference look:
```
c:\Innofactor\XrmToolBox.Plugin\Plugin\bin\Debug\Plugins
C:\Innofactor\XrmToolBox.Plugin\Plugin\bin\Debug\Plugins
```
But that difference let code start coping file to itself. And didn't let me debug. 
That PR will fix that behavior.
> Comparing string in lower case to avoid possible issues on some PCs

- XrmToolBox/New/PluginsForm.cs
- XrmToolBox/Options.cs
This is a partial feature solution to the requested [feature](https://github.com/MscrmTools/XrmToolBox/issues/1055). I have added new sort order type in the settings section called "Rating". I have also added capability so that this rating option is "remembered" in the next log in.
> Added code to add an extra option for sort order

- XrmToolBox.ToolLibrary/Forms/ToolLibraryForm.cs
- XrmToolBox.ToolLibrary/Forms/ToolLibraryForm.designer.cs
Use smaller icons for the filters. The original resource files are 32x32, so they are now resized in code to 24x24
Increased the width of the splitter to make it easier to grab
> New tool library

- XrmToolBox/New/NewForm.Designer.cs
- XrmToolBox/New/NewForm.cs
This is useful when you have multiple instance of XrmToolBox open :)
It's a bit confusing because the tabs are called "windows" too, so I labeled it "top level window" - probably could find something better but it's pretty clear once you try it.
> Add Window->"Name top level window:"

- XrmToolBox.ToolLibrary/Forms/ToolLibraryForm.cs
- XrmToolBox/New/EventArgs/PluginsListEventArgs.cs
- XrmToolBox/New/NewForm.cs
- XrmToolBox/New/PluginsForm.cs
- XrmToolBox/New/PluginsForm2.cs
This change will allow users to open the tool library from the "Open Tools Library" image button  with the search already set and filtered to their local search. This will hopefully provide a more streamlined experience to the user.
> Open the Tool Library with a default search when an installed tool cannot be found

- XrmToolBox.Extensibility/Manifest/ManifestLoader.cs
- XrmToolBox/PluginManagerExtended.cs
This is basically undoing the PluginExt use.  Works on my machine, when it wasn't working before for reloading.
> The Obsolete was a lie

- XrmToolBox.ToolLibrary/UserControls/ToolPackageProperties.cs
Only show the listed versions of the NuGet packages. This allows creators to hide versions that are unstable / have bugs.
_For the [msftPACE.FlowOwnershipAudit](https://www.nuget.org/packages/msftPACE.FlowOwnershipAudit/) tool, our initial versions crash the toolbox. This is a fix where we have unlisted the invalid versions_
> Only show the listed versions of the nuget packages. 

- XrmToolBox.ToolLibrary/ToolLibrary.cs
All files get put into the plugin folder when installing from nuget cache, rather than honoring the plugin nested folder structure.
> Fix for #1348

- XrmToolBox/New/NewForm.Community.cs
Now and then, I've seen these strange error, when a tool has interface IGitHubPlugin etc, and it breaks when trying to get the username/repository. The similar for PayPal, Help, etc.
Found when debugging:
```
Error Time: 2024-06-16 10:38:28.116
System.NullReferenceException
Object reference not set to an instance of an object.
XrmToolBox
at XrmToolBox.New.NewForm.GetGithubBaseUrl(String page)
at XrmToolBox.New.NewForm.githubPluginMenuItem_Click(Object sender, EventArgs e)
at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
at …
```
> When interfaces breaks, be more gentle
